# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

default:
  image: gradle:alpine
  
  before_script:
    - cd application
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - application/build
      - application/.gradle

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - application/build
      - application/.gradle

package-linux:
  image: gradle:latest
  only:
    refs:
      - tags
      - master
  stage: deploy
  before_script:
    - cd application
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME
    - apt update
    - apt install fakeroot -y
  script: gradle packageDeb
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - application/build
      - application/.gradle
  artifacts:
    paths:
      - application/build/compose/binaries/main/deb/notedown_1.0.0-1_amd64.deb
